import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import Search from "./components/Search";
import WhyChooseUs from "./components/WhyChooseUs";
import Places from "./components/Places";
import Explore from "./components/Explore";
import Features from "./components/Features";
import Customer from "./components/Customer";
import ContactUs from "./components/ContactUs";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          {/* <div className="container p-10">
          <Search/>
          </div> */}
          {/* <WhyChooseUs/>
          <Places/>
          <Explore/>
          <Features/>
          <Customer/>
          <ContactUs/> */}
          {/* <Footer/> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
